(define (go)
    (scope (include "../assoc.s"))
    (scope (include "../apply.s"))
    (scope (include "../a.s"))
    (scope (include "../block.s"))
    (scope (include "../call.s"))
    (scope (include "../chain.s"))
    (scope (include "../common.s"))
    (scope (include "../common2.s"))
    (scope (include "../common3.s"))
    (scope (include "../common4.s"))
    (scope (include "../defined.s"))
    (scope (include "../delay.s"))
    (scope (include "../except.s"))
    (scope (include "../extend.s"))
    (scope (include "../extension.s"))
    (scope (include "../arrays.s"))
    (go)
    )
(go)
    
