.\" A man page for the Scam programming language
.\" Contact lusth@cs.ua.edu to correct errors or omissions. 
.TH man 1 "1  August 2011" "0.1.0" "Scam man page"
.SH NAME
Scam \- a Scheme-like programming language with Sway features
.SH SYNOPSIS
.B scam 
.I fileName

.SH DESCRIPTION
.B Scam
is a programming language interpreter for the Scam Language.
The Scam language features Scheme syntax with the semantics of the
Sway programming language.
.SH AUTHOR
.nf
John C. Lusth (lusth@cs.ua.edu)
.fi
.SH INTERNET RESOURCES
Main website:  http://beastie.cs.ua.edu/scam
.SH HISTORY
23 August 2011 \- scam 0.1.0 - the first beta release
