#!/bin/bash
if [ $2server == server ] ; then
    SERVER=beastie.cs.ua.edu;
    echo putting to beastie;
else
    SERVER=nixie.cs.ua.edu;
    echo putting to $2;
fi
pdflatex index.tex
hyperlatex index.tex
makeindex index.idx
cp index.pdf book.pdf
fix index*.html
where=`uname -n`
echo On $where.cs.ua.edu...
if [ $where".cs.ua.edu" == $SERVER ]  ; then
    echo sending scam book files to $SERVER via direct copy...
    cp index.html *.html lusth.css *.tex book.pdf /var/www/scam/tsrm/;
else
    echo sending scam book files to $SERVER via ssh...
    scp index.html *.html lusth.css *.tex book.pdf $SERVER:/var/www/scam/tsrm/;
fi
