#!/bin/bash
if [ $2server == server ] ; then
    SERVER=beastie.cs.ua.edu;
    echo putting to beastie;
else
    SERVER=nixie.cs.ua.edu;
    echo putting to $2;
fi
name=`basename $1 .tex`
pdflatex $name.tex
hyperlatex $name.tex
echo sending $name.\* to $SERVER...
scp $name.tex $name.html $name.pdf $SERVER:/var/www/scam/
