#!/bin/bash
if [ $2server == server ] ; then
    SERVER=beastie.cs.ua.edu;
    echo putting to beastie;
else
    SERVER=nixie.cs.ua.edu;
    echo putting to $2;
fi
name=`basename $1 .tex`
echo sending css files to $SERVER...
scp lusth.css $SERVER:/var/www/scam/
scp lusth.css $SERVER:/var/www/scam/tsrm
cp lusth.css ../tsrm
